version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    runtime-versions:
      docker: 19
    # commands:
    #   - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #   - unzip awscliv2.zip
    #   - sh ./aws/install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
      # - /usr/local/bin/aws ecr-public get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin public.ecr.aws/p5d8w6d9
  build:
    commands:
      - docker build -t 446804614856.dkr.ecr.ap-northeast-2.amazonaws.com/street-builder:${TAG_NAME} .
      # - docker build -t public.ecr.aws/p5d8w6d9/street-builder:${TAG_NAME} .
      # - docker push public.ecr.aws/p5d8w6d9/street-builder:${TAG_NAME}
  post_build:
    commands:
      - docker push 446804614856.dkr.ecr.ap-northeast-2.amazonaws.com/street-builder:${TAG_NAME}
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths